server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/tutor
spring.datasource.username=webadmin
spring.datasource.password=SERczr74532
spring.datasource.driver-class-name=org.postgresql.Driver 